# Build settings
plugins:
  - jemoji
  - jekyll-paginate

# Site settings
title: "blog.whale"
description: > # this means to ignore newlines until "email:"
   My life story I guess.

email: weilon@weilonying.com
#blog logo
logo: "/assets/images/logo.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cover.jpg"

name: 'Weilon Ying'
author: 'Weilon Ying'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://blog.whale.moe" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: ''
instagram_url: 'https://instagram.com/weilonying'
feed: '/feed.xml'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/weilonying
    desc:	Find me on GitHub
    share_url:
    share_title:
    share_link:

  - icon: instagram
    url:  https://instagram.com/weilonying
    desc: Follow me on Instagram

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
